// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggDGhBSFP_I6bxvkBJFnlgUjWMX1kJS4',
    appId: '1:1018474349122:web:2f88ab197b4e4583ba63db',
    messagingSenderId: '1018474349122',
    projectId: 'egy-calender',
    authDomain: 'egy-calender.firebaseapp.com',
    storageBucket: 'egy-calender.firebasestorage.app',
    measurementId: 'G-RNEPQFC2M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4goq0HSwYAtb2y6oHDEGRW-VgTCvMr8',
    appId: '1:1018474349122:android:bcb6a618d304223aba63db',
    messagingSenderId: '1018474349122',
    projectId: 'egy-calender',
    storageBucket: 'egy-calender.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOVkk_eEXu8X29v1oJ8i84dwOdoOrem8',
    appId: '1:1018474349122:ios:9f84b57727a5548bba63db',
    messagingSenderId: '1018474349122',
    projectId: 'egy-calender',
    storageBucket: 'egy-calender.firebasestorage.app',
    iosClientId: '1018474349122-4dkpla9sr2rdjs0qdfviovqhsdui6ufs.apps.googleusercontent.com',
    iosBundleId: 'com.example.calender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOVkk_eEXu8X29v1oJ8i84dwOdoOrem8',
    appId: '1:1018474349122:ios:9f84b57727a5548bba63db',
    messagingSenderId: '1018474349122',
    projectId: 'egy-calender',
    storageBucket: 'egy-calender.firebasestorage.app',
    iosClientId: '1018474349122-4dkpla9sr2rdjs0qdfviovqhsdui6ufs.apps.googleusercontent.com',
    iosBundleId: 'com.example.calender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggDGhBSFP_I6bxvkBJFnlgUjWMX1kJS4',
    appId: '1:1018474349122:web:db5af0cfaadf1332ba63db',
    messagingSenderId: '1018474349122',
    projectId: 'egy-calender',
    authDomain: 'egy-calender.firebaseapp.com',
    storageBucket: 'egy-calender.firebasestorage.app',
    measurementId: 'G-B4PJ7N9JBX',
  );
  
}
